# Generated by Django 5.0.7 on 2024-07-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products_count',
            field=models.IntegerField(null=True),
        ),
    ]
