# Generated by Django 5.0.7 on 2024-07-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_count_category_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
    ]
